const home = document.getElementById("Home_button");
 const karte = document.getElementById("Karte_button");
 const aktivitaeten = document.getElementById("Aktivitaeten_button");





 home.addEventListener("click", function(){
   window.location.href = "../index.html";})

 karte.addEventListener("click", function(){
    window.location.href = "/pages/Karte.html";})

aktivitaeten.addEventListener("click",function(){
   window.location.href = "/pages/Aktivitäten.html";} )